version: '3.8'
services:
  pub1:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./data/pub1:/var/lib/postgresql/data
      - ./sql/create_table1.sql:/docker-entrypoint-initdb.d/create_table1.sql
      - ./sql/insert_data1.sql:/docker-entrypoint-initdb.d/insert_data1.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  pub2:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes: 
      - ./data/pub2:/var/lib/postgresql/data
      - ./sql/create_table2.sql:/docker-entrypoint-initdb.d/create_table2.sql
      - ./sql/insert_data2.sql:/docker-entrypoint-initdb.d/insert_data2.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  sub1:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes: 
      - ./data/sub1:/var/lib/postgresql/data
      - ./sql/create_table1.sql:/docker-entrypoint-initdb.d/create_table1.sql
      - ./sql/create_table2.sql:/docker-entrypoint-initdb.d/create_table2.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf


  sub2:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5435:5432'
    volumes: 
      - ./data/sub2:/var/lib/postgresql/data
      - ./sql/create_table1.sql:/docker-entrypoint-initdb.d/create_table1.sql
      - ./sql/create_table2.sql:/docker-entrypoint-initdb.d/create_table2.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf